[package]
name = "tetris"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
colored = "2.0"
crossterm = "0.26"
ratatui = "0.29.0"
rand = "0.8"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
